server:
  servlet:
    context-path: /routesandexplore/api/store
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  application:
    name: routes-explorations-api
  web:
    resources:
      add-mappings: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false


